### ISSUE TITLE
Import of Legacy sidecar rules fail in 3.0.x frontend

### ISSUE THREAD

**Issue by daniejstriata** [Graylog2/collector-sidecar#369]
### Problem description
I’m using a reverse proxy to access the graylog frontend and upgraded from 2.5.2 to 3.0.1 (and since then to 3.0.2) on Centos 7.6. (I was testing 3.x before I upgrade the rest of the graylog servers we use) I  got stuck when browsing to create new configurations for the Collectors. (I can access the Legacy sidecar collectors, no problem.)
https://example.com/system/sidecars/configuration/new
When I want to create the sidecar configuration. (Was also trying to import legacy configuration but nothing seemed to happen from clicking the link there.)

This is more related to the frontend. Not sure where to log it.

```
Cannot read property 'then' of undefined


Stack Trace:

TypeError: Cannot read property 'then' of undefined
    at r._reloadVariables (https://example.com/assets/5c4b4521-12.a5e2fb591e8fd54ee4ef.js:1:14630)
    at r.value (https://example.com/assets/5c4b4521-12.a5e2fb591e8fd54ee4ef.js:1:16845)
    at kn (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:89167)
    at Tn (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:84934)
    at gn (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:84286)
    at Rn (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:83307)
    at $t (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:82227)
    at Object.enqueueSetState (https://example.com/assets/vendor.4024e2a8db732781a971.js:18:47300)
    at n.W.setState (https://example.com/assets/vendor.4024e2a8db732781a971.js:26:1660)
    at n.safeSetState (https://example.com/assets/app.a5e2fb591e8fd54ee4ef.js:88:190298)
    at https://example.com/assets/app.a5e2fb591e8fd54ee4ef.js:88:189403

Component Stack:

    in r
    in div
    in b
    in p
    in div
    in b
    in div
    in p
    in p
    in Uncontrolled(p)
    in div
    in p
    in div
    in p
    in div
    in div
    in b
    in r
    in div
    in p
    in div
    in p
    in span
    in i
    in SidecarNewConfigurationPage
    in n
    in div
    in p
    in div
    in p
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```
### Steps to reproduce the problem
1. Login to Graylog
2. Select System
3. Select Sidecars
4. Select "Create Configuration"
Does this:
![image](https://user-images.githubusercontent.com/13314239/59038283-12d3d580-8873-11e9-9a61-ad1493f9ea53.png)

### Environment
* Sidecar Version: N/A
* Graylog Version: 3.0.2
* Operating System: Centos 7.6
* Elasticsearch Version:    "version" : {
    "number" : "5.6.16",
    "build_hash" : "3a740d1",
    "build_date" : "2019-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
* MongoDB Version: mongodb-org-server-4.0.10-1.el7.x86_64

**Comment by kroepke** [comment]
We were unable to reproduce this issue with a reverse proxy setup.
Could you please describe your setup here so we can figure out what is different for you?

**Comment by daniejstriata** [comment]
Thanks for the info. It made me think and I disabled my server's CSP policy. That solved my issue. It used to work fine for version 2.5 but I'll need to tweak it for 3.x. What threw me off was that Chrome did not tell met it was a CSP related issue as it has for any other CSP implementation I've done for other web applications before. Now I just need to figure out what is breaking only the config portion of Graylog 3 with the following rule.

I added to my nginx config:
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'; frame-src; object-src 'none'; frame-ancestors 'none'; form-action 'self';";

From Chrome console I get this:(Full output attached)
vendor.4024e2a8db732781a971.js:18 TypeError: Cannot read property 'then' of undefined
    at r._reloadVariables (ConfigurationVariablesHelper.jsx:30)
    at r.value (ConfigurationVariablesHelper.jsx:26)
    at kn (vendor.4024e2a8db732781a971.js:18)
    at Tn (vendor.4024e2a8db732781a971.js:18)
    at gn (vendor.4024e2a8db732781a971.js:18)
    at Rn (vendor.4024e2a8db732781a971.js:18)
    at $t (vendor.4024e2a8db732781a971.js:18)
    at Object.enqueueSetState (vendor.4024e2a8db732781a971.js:18)
    at n.W.setState (vendor.4024e2a8db732781a971.js:26)
    at n.safeSetState (loadable-components.es.js:216)
    at loadable-components.es.js:198
[example.com-1560407965975.log](https://github.com/Graylog2/collector-sidecar/files/3284501/example.com-1560407965975.log)

**Comment by jalogisch** [comment]
Glad that you have fixed your issue @daniejstriata 

If you want to discuss or debug your proxy configuration, please jump over to the community.
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
