### ISSUE TITLE
Loading component failed: n is undefined when accessing Sidecar Configuration menu

### ISSUE THREAD

**Issue by jivepig** [Graylog2/collector-sidecar#455]
### Problem description
Sidecars fully functional, however RC2 unable to load configuration tab in Sidecar Configuration.

### Steps to reproduce the problem

1. ...Go to System->Sidecars, then in the new tab menu select Configuration.
2. Page will not load and get error "Loading component failed: n is undefined"

### Environment
Docker Single Node
* Sidecar Version: 1.3beta
* Graylog Version:RC2
* Operating System:Windows
* Elasticsearch Version:opensearch V2.0
* MongoDB Version: V5.0

**Comment by dennisoelkers** [comment]
I tried to verify this on any of the test instances and it worked. Are there any steps missing to reproduce it?

**Comment by jivepig** [comment]
Here are the web console logs from Firefox and from Chrome:

Firefox
################################################

TypeError: n is undefined
    s OperatingSystemIcon.tsx:32
    Jr vendor.1e79e27aeb952fbe940b.js:2
    _a vendor.1e79e27aeb952fbe940b.js:2
    fb vendor.1e79e27aeb952fbe940b.js:2
    lb vendor.1e79e27aeb952fbe940b.js:2
    ab vendor.1e79e27aeb952fbe940b.js:2
    p vendor.1e79e27aeb952fbe940b.js:2
    unstable_runWithPriority vendor.1e79e27aeb952fbe940b.js:2
    Up vendor.1e79e27aeb952fbe940b.js:2
    $p vendor.1e79e27aeb952fbe940b.js:2
    Kp vendor.1e79e27aeb952fbe940b.js:2
    nb vendor.1e79e27aeb952fbe940b.js:2
    enqueueSetState vendor.1e79e27aeb952fbe940b.js:2
    setState vendor.1e79e27aeb952fbe940b.js:2
    p vendor.1e79e27aeb952fbe940b.js:2
    n vendor.1e79e27aeb952fbe940b.js:2
    emit vendor.1e79e27aeb952fbe940b.js:2
    trigger vendor.1e79e27aeb952fbe940b.js:2
    propagateChanges CollectorsStore.js:62
    all CollectorsStore.js:106
    promise callback*value CancellablePromise.ts:30
    all CollectorsStore.js:103
    n vendor.1e79e27aeb952fbe940b.js:2
    emit vendor.1e79e27aeb952fbe940b.js:2
    trigger vendor.1e79e27aeb952fbe940b.js:2
    triggerAsync vendor.1e79e27aeb952fbe940b.js:2
    <anonymous> task.js:61
    C task.js:35
    S task.js:46
    BwUargNX task.js:84
	
Chrome
#########################################################
vendor.1e79e27aeb952fbe940b.js:2 TypeError: Cannot read properties of undefined (reading 'trim')
    at s (OperatingSystemIcon.tsx:68:60)
    at Jr (vendor.1e79e27aeb952fbe940b.js:2:810240)
    at _a (vendor.1e79e27aeb952fbe940b.js:2:856166)
    at fb (vendor.1e79e27aeb952fbe940b.js:2:848941)
    at lb (vendor.1e79e27aeb952fbe940b.js:2:848866)
    at ab (vendor.1e79e27aeb952fbe940b.js:2:845896)
    at vendor.1e79e27aeb952fbe940b.js:2:797644
    at exports.unstable_runWithPriority (vendor.1e79e27aeb952fbe940b.js:2:872944)
    at Up (vendor.1e79e27aeb952fbe940b.js:2:797353)
    at $p (vendor.1e79e27aeb952fbe940b.js:2:797589)
    at Kp (vendor.1e79e27aeb952fbe940b.js:2:797524)
    at nb (vendor.1e79e27aeb952fbe940b.js:2:842681)
    at Object.enqueueSetState (vendor.1e79e27aeb952fbe940b.js:2:801309)
    at h.setState (vendor.1e79e27aeb952fbe940b.js:2:903650)
    at t.p (vendor.1e79e27aeb952fbe940b.js:2:920406)
    at p.n (vendor.1e79e27aeb952fbe940b.js:2:911149)
    at p.emit (vendor.1e79e27aeb952fbe940b.js:2:56891)
    at z.trigger (vendor.1e79e27aeb952fbe940b.js:2:912030)
    at z.propagateChanges (CollectorsStore.js:62:12)
    at CollectorsStore.js:106:18
pa @ vendor.1e79e27aeb952fbe940b.js:2
loadAsync.tsx:28 TypeError: Cannot read properties of undefined (reading 'trim')
    at s (OperatingSystemIcon.tsx:68:60)
    at Jr (vendor.1e79e27aeb952fbe940b.js:2:810240)
    at _a (vendor.1e79e27aeb952fbe940b.js:2:856166)
    at fb (vendor.1e79e27aeb952fbe940b.js:2:848941)
    at lb (vendor.1e79e27aeb952fbe940b.js:2:848866)
    at ab (vendor.1e79e27aeb952fbe940b.js:2:845896)
    at vendor.1e79e27aeb952fbe940b.js:2:797644
    at exports.unstable_runWithPriority (vendor.1e79e27aeb952fbe940b.js:2:872944)
    at Up (vendor.1e79e27aeb952fbe940b.js:2:797353)
    at $p (vendor.1e79e27aeb952fbe940b.js:2:797589)
    at Kp (vendor.1e79e27aeb952fbe940b.js:2:797524)
    at nb (vendor.1e79e27aeb952fbe940b.js:2:842681)
    at Object.enqueueSetState (vendor.1e79e27aeb952fbe940b.js:2:801309)
    at h.setState (vendor.1e79e27aeb952fbe940b.js:2:903650)
    at t.p (vendor.1e79e27aeb952fbe940b.js:2:920406)
    at p.n (vendor.1e79e27aeb952fbe940b.js:2:911149)
    at p.emit (vendor.1e79e27aeb952fbe940b.js:2:56891)
    at z.trigger (vendor.1e79e27aeb952fbe940b.js:2:912030)
    at z.propagateChanges (CollectorsStore.js:62:12)
    at CollectorsStore.js:106:18

**Comment by mpfz0r** [comment]
not a real bug, but will be improved with 
 https://github.com/Graylog2/graylog2-server/pull/14104
